/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as TherapistRouteImport } from './routes/therapist'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PanicRouteImport } from './routes/panic'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as MeditateRouteImport } from './routes/meditate'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CbtRouteImport } from './routes/cbt'
import { Route as AiSettingsRouteImport } from './routes/ai-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelapseHabitIdRouteImport } from './routes/relapse.$habitId'
import { Route as HabitsHabitIdRouteImport } from './routes/habits.$habitId'

const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistRoute = TherapistRouteImport.update({
  id: '/therapist',
  path: '/therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicRoute = PanicRouteImport.update({
  id: '/panic',
  path: '/panic',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditateRoute = MeditateRouteImport.update({
  id: '/meditate',
  path: '/meditate',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CbtRoute = CbtRouteImport.update({
  id: '/cbt',
  path: '/cbt',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSettingsRoute = AiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelapseHabitIdRoute = RelapseHabitIdRouteImport.update({
  id: '/relapse/$habitId',
  path: '/relapse/$habitId',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsHabitIdRoute = HabitsHabitIdRouteImport.update({
  id: '/$habitId',
  path: '/$habitId',
  getParentRoute: () => HabitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-settings': typeof AiSettingsRoute
  '/cbt': typeof CbtRoute
  '/coach': typeof CoachRoute
  '/habits': typeof HabitsRouteWithChildren
  '/identity': typeof IdentityRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/meditate': typeof MeditateRoute
  '/milestones': typeof MilestonesRoute
  '/panic': typeof PanicRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/storage': typeof StorageRoute
  '/therapist': typeof TherapistRoute
  '/toolkit': typeof ToolkitRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/relapse/$habitId': typeof RelapseHabitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-settings': typeof AiSettingsRoute
  '/cbt': typeof CbtRoute
  '/coach': typeof CoachRoute
  '/habits': typeof HabitsRouteWithChildren
  '/identity': typeof IdentityRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/meditate': typeof MeditateRoute
  '/milestones': typeof MilestonesRoute
  '/panic': typeof PanicRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/storage': typeof StorageRoute
  '/therapist': typeof TherapistRoute
  '/toolkit': typeof ToolkitRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/relapse/$habitId': typeof RelapseHabitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-settings': typeof AiSettingsRoute
  '/cbt': typeof CbtRoute
  '/coach': typeof CoachRoute
  '/habits': typeof HabitsRouteWithChildren
  '/identity': typeof IdentityRoute
  '/insights': typeof InsightsRoute
  '/journal': typeof JournalRoute
  '/meditate': typeof MeditateRoute
  '/milestones': typeof MilestonesRoute
  '/panic': typeof PanicRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/storage': typeof StorageRoute
  '/therapist': typeof TherapistRoute
  '/toolkit': typeof ToolkitRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/relapse/$habitId': typeof RelapseHabitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-settings'
    | '/cbt'
    | '/coach'
    | '/habits'
    | '/identity'
    | '/insights'
    | '/journal'
    | '/meditate'
    | '/milestones'
    | '/panic'
    | '/reports'
    | '/settings'
    | '/share'
    | '/storage'
    | '/therapist'
    | '/toolkit'
    | '/habits/$habitId'
    | '/relapse/$habitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-settings'
    | '/cbt'
    | '/coach'
    | '/habits'
    | '/identity'
    | '/insights'
    | '/journal'
    | '/meditate'
    | '/milestones'
    | '/panic'
    | '/reports'
    | '/settings'
    | '/share'
    | '/storage'
    | '/therapist'
    | '/toolkit'
    | '/habits/$habitId'
    | '/relapse/$habitId'
  id:
    | '__root__'
    | '/'
    | '/ai-settings'
    | '/cbt'
    | '/coach'
    | '/habits'
    | '/identity'
    | '/insights'
    | '/journal'
    | '/meditate'
    | '/milestones'
    | '/panic'
    | '/reports'
    | '/settings'
    | '/share'
    | '/storage'
    | '/therapist'
    | '/toolkit'
    | '/habits/$habitId'
    | '/relapse/$habitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSettingsRoute: typeof AiSettingsRoute
  CbtRoute: typeof CbtRoute
  CoachRoute: typeof CoachRoute
  HabitsRoute: typeof HabitsRouteWithChildren
  IdentityRoute: typeof IdentityRoute
  InsightsRoute: typeof InsightsRoute
  JournalRoute: typeof JournalRoute
  MeditateRoute: typeof MeditateRoute
  MilestonesRoute: typeof MilestonesRoute
  PanicRoute: typeof PanicRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  StorageRoute: typeof StorageRoute
  TherapistRoute: typeof TherapistRoute
  ToolkitRoute: typeof ToolkitRoute
  RelapseHabitIdRoute: typeof RelapseHabitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist': {
      id: '/therapist'
      path: '/therapist'
      fullPath: '/therapist'
      preLoaderRoute: typeof TherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panic': {
      id: '/panic'
      path: '/panic'
      fullPath: '/panic'
      preLoaderRoute: typeof PanicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditate': {
      id: '/meditate'
      path: '/meditate'
      fullPath: '/meditate'
      preLoaderRoute: typeof MeditateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbt': {
      id: '/cbt'
      path: '/cbt'
      fullPath: '/cbt'
      preLoaderRoute: typeof CbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-settings': {
      id: '/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relapse/$habitId': {
      id: '/relapse/$habitId'
      path: '/relapse/$habitId'
      fullPath: '/relapse/$habitId'
      preLoaderRoute: typeof RelapseHabitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$habitId': {
      id: '/habits/$habitId'
      path: '/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof HabitsHabitIdRouteImport
      parentRoute: typeof HabitsRoute
    }
  }
}

interface HabitsRouteChildren {
  HabitsHabitIdRoute: typeof HabitsHabitIdRoute
}

const HabitsRouteChildren: HabitsRouteChildren = {
  HabitsHabitIdRoute: HabitsHabitIdRoute,
}

const HabitsRouteWithChildren =
  HabitsRoute._addFileChildren(HabitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSettingsRoute: AiSettingsRoute,
  CbtRoute: CbtRoute,
  CoachRoute: CoachRoute,
  HabitsRoute: HabitsRouteWithChildren,
  IdentityRoute: IdentityRoute,
  InsightsRoute: InsightsRoute,
  JournalRoute: JournalRoute,
  MeditateRoute: MeditateRoute,
  MilestonesRoute: MilestonesRoute,
  PanicRoute: PanicRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  StorageRoute: StorageRoute,
  TherapistRoute: TherapistRoute,
  ToolkitRoute: ToolkitRoute,
  RelapseHabitIdRoute: RelapseHabitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
